# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imgrawr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=imgrawr.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date published')),
                ('original_filename', models.CharField(default=None, max_length=200)),
                ('filename', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgrawr.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_text', models.CharField(default=imgrawr.models.generate_id, editable=False, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='imagestags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgrawr.Tag'),
        ),
    ]
