# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgrawr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTagVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.BigIntegerField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgrawr.Image')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgrawr.Tag')),
            ],
        ),
    ]
