# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgrawr', '0004_auto_20161129_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestags',
            name='tag',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
